### ISSUE TITLE
Add Sentry integration

### ISSUE THREAD

**Issue by duffn** [duffn/grape-api-boilerplate#113]
Add the ability to include a Sentry integration. https://docs.sentry.io/platforms/ruby/guides/rack/

**Comment by Aaryanpal** [comment]
Hu @duffn …
I would like to give it a shot

**Comment by duffn** [comment]
Oh my, thanks for your interest! I just happened to open a PR almost as the same time you posted! https://github.com/duffn/grape-api-boilerplate/pull/116

There is also an issue for making the requesting logging middleware optional if you'd be interested in that one? https://github.com/duffn/grape-api-boilerplate/issues/114

Again, thank you for showing interest!
